### ISSUE TITLE
Agent Donut

### ISSUE THREAD

**Issue by Solarlight1** [cusi-dev/SupportDashboard#6]
What layout should the array be in to get data to appear in the donut.

For testing I am sending 

mydata = [
{ label:'Mark', value:5 },
{ label:'Dave', value:2 },
{ label:'unassigned', value:10}
]

but the donut stays blank

**Comment by Solarlight1** [comment]
data = [
  { label: "Label1", value: 16 },
  { label: "Label2", value: 34 },
  { label: "Label3", value: 10 },
  { label: "Label4", value: 40 },
  { label: "Label5", value: 20 },
]
		send_event('resolved', { value: data })

**Comment by derekbjohnson** [comment]
Hello!  It looks like you may have answered your own question, but I wanted to make sure.  We implemented our donut chart from [mattia72/FullPie.md](https://gist.github.com/mattia72/8168893).  Your second post looks correct.  It's also important to occasionally refresh the data using [this script](https://github.com/cusi-dev/SupportDashboard/blob/master/resources/PS/POST-DASHBOARD-REFRESH.ps1)

Please let me know if we can be of any additional assistance, @Solarlight1!

**Comment by Solarlight1** [comment]
Hmmm - I cannot get it to work - the donut is blank - I have setup the job, and have the job outputting to the command line so I know it is being run - no errors, but still no data also. Can you help.

Below is the job
---------------------
#!/usr/bin/env ruby
require 'net/http'
require 'uri'
 

def self.get(url)
    uri=URI(url)
    http=Net::HTTP.new(uri.host, uri.port)
    http.use_ssl=false
    #http.verify_mode=OpenSSL::SSL::VERIFY_NONE

    request=Net::HTTP::Get.new(uri.request_uri)

    response=http.request(request)

    if response.code != '200'
        raise "failed to get #{url} due to #{response.code}"
    end

    return response.body
end
 
def to_numeric(str)
  Integer(str)
rescue
  Float(str) if Float(str) rescue nil
end

SCHEDULER.every '10s', :first_in => 0 do |job|

data = [
  { label: "Label1", value: 16 },
  { label: "Label2", value: 34 },
  { label: "Label3", value: 10 },
  { label: "Label4", value: 40 },
  { label: "Label5", value: 20 }
]
		send_event("resolved", { data: data })
		
    print "Agent Stats\n"
end

-----------------

Some of the program has not been implemented yet, for example the data feed will come from a string returned from a website,

Your help is much appreciated

Mark

**Comment by derekbjohnson** [comment]
Hi, @Solarlight1.  I wanted to make sure you saw [our examples using PowerShell](SupportDashboard/resources/PS/POST-TO-DASHBOARD.ps1)  In that file, there's an example starting at line 247.  Can you confirm the following?

1. You are performing an HTTP POST to your widget at `$($dashboardURL)/widgets/YourWidgetName`
2. The JSON you're sending includes the authorization token.  I don't see this part in your sample code.  It won't accept the data without the authorization token.
